# Allow OP Players to bypass the plugin
op-bypass: true

# Allows Creative Players to bypass the plugin
creative-bypass: true

# Message for all types that don't have a specific message
global-message: "§cYou can't do that!"

blocks:
  # Below is an example! Make sure to always provide the fields, even when they are empty!
  #- material: DIAMOND_BLOCK
  #  types:
  #    - place:
  #       - use: true
  #       - message: "§cYou can't place diamond blocks!"
  #    - break:
#        - use: true
  #      - message: "§cYou can't place diamond blocks!"
  #  levels:
  #    - mining: 5
  #  worlds:
  #    - world